# Generated by Django 4.0.4 on 2022-04-18 11:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('serial_no', models.CharField(max_length=50, unique=True)),
                ('ip', models.GenericIPAddressField()),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
